name: marks.dev Build and Release Pipeline
on:
  push:
    branches: [ 'main' ]

jobs:
  Build-Site-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Get Git Short Shahash
        id: new_sha
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Check new sha hash
        run: echo ${{ steps.new_sha.outputs.sha_short }}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/arm/v7
          push: true
          tags: |
            eaglerock/marks.dev:latest
            eaglerock/marks.dev:${{ steps.new_sha.outputs.sha_short }}
    outputs:
      new_sha: ${{ steps.new_sha.outputs.sha_short }}

  Publish-HLC-Site:
    runs-on: ubuntu-latest
    needs: Build-Site-Image
    steps:
      - name: Check out HLC repo code
        uses: actions/checkout@v4
        with:
          repository: eaglerock1337/happy-little-cloud
          token: ${{ secrets.HLC_GITHUB_TOKEN }}
      - name: Get Old Version from Chart yaml
        id: old_sha
        run: echo "sha_short=$(grep appVersion marks.dev/Chart.yaml | cut -f2 -d'"')" >> $GITHUB_OUTPUT
      - name: Check old sha hash
        run: echo ${{ steps.old_sha.outputs.sha_short }}
      - name: Set Git Name
        run: git config --global user.name "Autobob"
      - name: Set Git Email
        run: git config --global user.email "bob@marks.dev"
      - name: Swap Git Tag in Chart.yaml
        run: sed -i /appVersion/s/${{ steps.old_sha.outputs.sha_short }}/${{ needs.Build-Site-Image.outputs.new_sha }}/ marks.dev/Chart.yaml
      - name: Commit New Version to GitHub
        run: git commit -am "Update marks.dev site to use ${{ needs.Build-Site-Image.outputs.new_sha }} tag" && git push
