name: Release

on:
  push:
    branches:
      - main
      - alpha
      - beta

permissions:
  contents: write # Needed to create tags and releases
  issues: write # Needed to comment on issues
  pull-requests: write # Needed to comment on PRs

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for changelog generation
          token: ${{ secrets.SEMANTIC_RELEASE_TOKEN }} # Use PAT to bypass branch protection

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git for Autobob
        run: |
          git config user.name "Autobob"
          git config user.email "bob@marks.dev"

      - name: Analyze commits and determine version
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release --dry-run

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
